### ISSUE TITLE
Cant Build (Powershell)

### ISSUE THREAD

**Issue by Enzyy** [Marc3842h/Titan#21]
## Description

Hello, i try to build the script since about 4 hours.
I use Powershell

## What i have done 

- Reinstalled Win 10 + every Net-Framework, tried Win 7 too

## Errors

(Sorry for German language)

```
Bootstrap\Options.cs(24,51): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(27,52): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(30,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(33,46): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(36,47): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(39,48): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(42,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(45,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(48,43): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(55,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(60,41): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Sharecode\ShareCode.cs(78,20): error CS1056: Unerwartetes Zeichen '$'. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
"C:\Users\jta6\Desktop\Titan\Titan.sln" (Build Ziel) (1) ->
"C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj" (Standardziel) (2) ->
(CoreCompile Ziel) ->
  Bootstrap\Options.cs(24,51): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(27,52): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(30,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(33,46): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(36,47): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(39,48): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(42,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(45,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(48,43): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(55,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(60,41): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Sharecode\ShareCode.cs(78,20): error CS1056: Unerwartetes Zeichen '$'. [C:\Users\jta6\Desktop\Titan\Titan\Titan.cspro
j]

    1 Warnung(en)
    12 Fehler

Verstrichene Zeit 00:00:02.08
An error occurred when executing task 'Build'.
Error: MSBuild: Process returned an error (exit code 1).
```

**Comment by Marc3842h** [comment]
Which .NET Framework Version do you have installed? 

_Btw the german is no problem, I'm from Switzerland_

**Comment by Enzyy** [comment]
I have: 3.5 & 4.7 installed.

**Comment by Marc3842h** [comment]
Can you try to remove the .NET Framework 3.5? Titan requires atleast the .NET Framework 4.5.

**Comment by Enzyy** [comment]
Thanks. I tried it but still dont work (Got the same error)

**Comment by Enzyy** [comment]
Maybe this helps too: 
Fehler beim Buildvorgang.

```
"C:\Users\jta6\Desktop\Titan\Titan.sln" (Build Ziel) (1) ->
"C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj" (Standardziel) (2) ->
(ResolveAssemblyReferences Ziel) ->
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: Konflikte zwischen
 verschiedenen Versionen der gleichen abhängigen Assembly wurden gefunden. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csp
roj]
```

**Comment by Marc3842h** [comment]
Nope, isn't important as its just a warning and not the error.
Can you give me the **complete** build log?

**Comment by Enzyy** [comment]
```
PS C:\Users\jta6\Desktop\Titan> .\build.ps1
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Compiling build script...

========================================
Clean
========================================
Executing task: Clean
Cleaning directory C:/Users/jta6/Desktop/Titan/Titan/bin/Release
Finished executing task: Clean

========================================
Restore-NuGet-Packages
========================================
Executing task: Restore-NuGet-Packages
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'D:\Programme\Visual Studio 2017\MSBuild\15.0\bin'.
Alle in "packages.config" aufgeführten Pakete sind bereits installiert.
Finished executing task: Restore-NuGet-Packages

========================================
Build
========================================
Executing task: Build
Microsoft (R)-Buildmodul, Version 4.7.2053.0
[Microsoft .NET Framework, Version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Si
e den Schalter "/m" hinzufügen.
Der Buildvorgang wurde am 25.06.2017 12:37:17 gestartet.
Projekt "C:\Users\jta6\Desktop\Titan\Titan.sln" auf Knoten "1", Build Ziel(e).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Release|Any CPU" wird erstellt.
Das Projekt "C:\Users\jta6\Desktop\Titan\Titan.sln" (1) erstellt "C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj" (2) a
uf Knoten "1" (Standardziele).
Die Projektdatei enthält ToolsVersion="14.0". Dieses Toolset ist möglicherweise nicht bekannt oder nicht vorhanden. In
diesem Fall können Sie das Problem möglicherweise beheben, indem Sie die entsprechende Version von MSBuild installieren
. Oder für den Build wurde aufgrund der Richtlinie eine bestimmte ToolsVersion erzwungen. Das Projekt wird behandelt, a
ls enthielte es ToolsVersion="4.0". Weitere Informationen finden Sie unter http://go.microsoft.com/fwlink/?LinkId=29133
3.
ResolveAssemblyReferences:
  Führen Sie ggf. mit app.config eine erneute Zuordnung der Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2
  a6aeed-Assembly von Version 9.0.0.0 [] zu 10.0.0.0 [C:\Users\jta6\Desktop\Titan\packages\Newtonsoft.Json.10.0.2\lib\n
  et45\Newtonsoft.Json.dll] durch, um den Konflikt zu lösen und Warnmeldungen zu vermeiden.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: Konflikte zwischen v
erschiedenen Versionen der gleichen abhängigen Assembly wurden gefunden. [C:\Users\jta6\Desktop\Titan\Titan\Titan.cspro
j]
GenerateTargetFrameworkMonikerAttribute:
Das Ziel "GenerateTargetFrameworkMonikerAttribute" wird übersprungen, da alle Ausgabedateien hinsichtlich der Eingabeda
teien aktuell sind.
CoreCompile:
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitp
  referred /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:C:\Users\jta6\Desktop\Titan\packages\Co
  mmandLineParser.1.9.71\lib\net45\CommandLine.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Common.Logging.Core.
  3.3.1\lib\net40\Common.Logging.Core.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Common.Logging.3.3.1\lib\net4
  0\Common.Logging.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Common.Logging.Serilog.4.1.11\lib\net45\Common.L
  ogging.Serilog.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Eto.Forms.2.4.0-build1054\lib\net45\Eto.dll /refer
  ence:C:\Users\jta6\Desktop\Titan\packages\Eto.Platform.Gtk.2.4.0-build1054\lib\net45\Eto.Gtk2.dll /reference:C:\Users
  \jta6\Desktop\Titan\packages\Eto.Platform.Mac.2.4.0-build1054\lib\net45\Eto.Mac.dll /reference:C:\Users\jta6\Desktop\
  Titan\packages\Eto.Platform.Wpf.2.4.0-build1054\lib\net45\Eto.Wpf.dll /reference:"C:\Program Files (x86)\Reference As
  semblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:C:\Users\jta6\Desktop\Titan\packages
  \Mono.CSharp.4.0.0.143\lib\4.5\Mono.CSharp.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Mono.Posix.4.0.0.0\lib
  \net40\Mono.Posix.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Eto.Platform.Mac.2.4.0-build1054\lib\net45\Mono
  Mac.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll"
  /reference:C:\Users\jta6\Desktop\Titan\packages\Newtonsoft.Json.10.0.2\lib\net45\Newtonsoft.Json.dll /reference:C:\Us
  ers\jta6\Desktop\Titan\packages\protobuf-net.2.0.0.668\lib\net40\protobuf-net.dll /reference:C:\Users\jta6\Desktop\Ti
  tan\packages\Quartz.2.5.0\lib\net40\Quartz.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Serilog.2.4.0\lib\net4
  5\Serilog.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Serilog.Enrichers.Thread.3.0.0\lib\net45\Serilog.Enrich
  ers.Thread.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Serilog.Sinks.Async.1.0.1\lib\net45\Serilog.Sinks.Asyn
  c.dll /reference:C:\Users\jta6\Desktop\Titan\packages\Serilog.Sinks.File.3.2.0\lib\net45\Serilog.Sinks.File.dll /refe
  rence:C:\Users\jta6\Desktop\Titan\packages\Serilog.Sinks.Literate.2.1.0\lib\net45\Serilog.Sinks.Literate.dll /referen
  ce:C:\Users\jta6\Desktop\Titan\packages\Serilog.Sinks.RollingFile.3.3.0\lib\net45\Serilog.Sinks.RollingFile.dll /refe
  rence:C:\Users\jta6\Desktop\Titan\packages\SteamAuth.1.1.0\lib\net45\SteamAuth.dll /reference:C:\Users\jta6\Desktop\T
  itan\packages\SteamKit2.1.8.3\lib\net45\SteamKit2.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microso
  ft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fr
  amework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies
  \Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
  osoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram
  ework\.NETFramework\v4.5\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Frame
  work\.NETFramework\v4.5\System.Numerics.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framew
  ork\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.N
  ETFramework\v4.5\System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NE
  TFramework\v4.5\Facades\System.Collections.Concurrent.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Mi
  crosoft\Framework\.NETFramework\v4.5\Facades\System.Collections.dll" /reference:"C:\Program Files (x86)\Reference Ass
  emblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.Annotations.dll" /reference:"C:\Program
  Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.dll" /reference
  :"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.Ev
  entBasedAsync.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Fac
  ades\System.Diagnostics.Contracts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.N
  ETFramework\v4.5\Facades\System.Diagnostics.Debug.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micros
  oft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Tools.dll" /reference:"C:\Program Files (x86)\Reference A
  ssemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files
   (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Dynamic.Runtime.dll" /reference:"C:
  \Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Globalization.dll" /r
  eference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.IO.dll" /
  reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.dll
  " /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.
  Expressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facad
  es\System.Linq.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramewor
  k\v4.5\Facades\System.Linq.Queryable.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework
  \.NETFramework\v4.5\Facades\System.Net.NetworkInformation.dll" /reference:"C:\Program Files (x86)\Reference Assemblie
  s\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Net.Primitives.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Net.Requests.dll" /reference:"C:\Program Files (
  x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ObjectModel.dll" /reference:"C:\Progr
  am Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.dll" /reference:
  "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Emit.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Refl
  ection.Emit.ILGeneration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramewo
  rk\v4.5\Facades\System.Reflection.Emit.Lightweight.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micro
  soft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Extensions.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Primitives.dll" /reference:"C:\Progra
  m Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Resources.ResourceManager.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runt
  ime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\Syste
  m.Runtime.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v
  4.5\Facades\System.Runtime.InteropServices.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fra
  mework\.NETFramework\v4.5\Facades\System.Runtime.InteropServices.WindowsRuntime.dll" /reference:"C:\Program Files (x8
  6)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Numerics.dll" /reference:"C:\Pr
  ogram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Serialization.Js
  on.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System
  .Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.N
  ETFramework\v4.5\Facades\System.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblie
  s\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Security.Principal.dll" /reference:"C:\Program Files (x86)\Re
  ference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Duplex.dll" /reference:"C:\Prog
  ram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Http.dll" /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceMod
  el.NetTcp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades
  \System.ServiceModel.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NET
  Framework\v4.5\Facades\System.ServiceModel.Security.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
  osoft\Framework\.NETFramework\v4.5\Facades\System.Text.Encoding.dll" /reference:"C:\Program Files (x86)\Reference Ass
  emblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Fi
  les (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Text.RegularExpressions.dll" /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Threading.
  dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Th
  reading.Tasks.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Fac
  ades\System.Threading.Tasks.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework
  \.NETFramework\v4.5\Facades\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
  osoft\Framework\.NETFramework\v4.5\Facades\System.Xml.XDocument.dll" /reference:"C:\Program Files (x86)\Reference Ass
  emblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Xml.XmlSerializer.dll" /debug:pdbonly /filealign:512 /o
  ptimize+ /out:obj\Release\Titan.exe /subsystemversion:6.00 /resource:Resources\Steam.ico,Titan.Resources.Steam.ico /r
  esource:Resources\Exit.ico,Titan.Resources.Exit.ico /resource:Resources\Info.ico,Titan.Resources.Info.ico /resource:R
  esources\CSGO.ico,Titan.Resources.CSGO.ico /resource:Resources\Logo.ico,Titan.Resources.Logo.ico /resource:Resources\
  JsonLint.ico,Titan.Resources.JsonLint.ico /resource:Resources\SteamIO.ico,Titan.Resources.SteamIO.ico /target:exe /ut
  f8output Account\Impl\ProtectedAccount.cs Account\Impl\UnprotectedAccount.cs Account\Result.cs Account\TitanAccount.c
  s Bans\BanInfo.cs Bans\BanManager.cs Bootstrap\Options.cs Json\GitHubResponse.cs Json\JsonIndex.cs Json\JsonAccounts.
  cs Json\Victims.cs Logging\LogCreator.cs Logging\VictimTracker.cs Managers\AccountManager.cs Meta\CommendInfo.cs Meta
  \ReportInfo.cs Sharecode\ShareCode.cs Sharecode\ShareCodeInfo.cs Managers\ThreadManager.cs Titan.cs Properties\Assemb
  lyInfo.cs UI\2FA\TwoFactorAuthForm.cs UI\About\AboutUI.cs UI\Accounts\AccountUI.cs UI\APIKey\APIKeyForm.cs UI\APIKey\
  Commands\SteamKeySite.cs UI\General\General.cs UI\SharedResources.cs UI\UIManager.cs UI\UIType.cs Util\ArrayUtil.cs U
  til\SharecodeUtil.cs Util\SteamUtil.cs Util\StringUtil.cs Util\TimeUtil.cs Util\WaitFor.cs Web\WebAPIKeyResolver.cs "
  C:\Users\jta6\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
Bootstrap\Options.cs(24,51): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(27,52): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(30,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(33,46): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(36,47): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(39,48): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(42,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(45,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(48,43): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(55,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Bootstrap\Options.cs(60,41): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklaratio
n. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Sharecode\ShareCode.cs(78,20): error CS1056: Unerwartetes Zeichen '$'. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
Die Erstellung des Projekts "C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj" ist abgeschlossen (Standardziele) -- FEHLE
R.

Das Projekt "C:\Users\jta6\Desktop\Titan\Titan.sln" (1) erstellt "C:\Users\jta6\Desktop\Titan\TitanTest\TitanTest.cspro
j" (3) auf Knoten "1" (Standardziele).
Die Projektdatei enthält ToolsVersion="14.0". Dieses Toolset ist möglicherweise nicht bekannt oder nicht vorhanden. In
diesem Fall können Sie das Problem möglicherweise beheben, indem Sie die entsprechende Version von MSBuild installieren
. Oder für den Build wurde aufgrund der Richtlinie eine bestimmte ToolsVersion erzwungen. Das Projekt wird behandelt, a
ls enthielte es ToolsVersion="4.0". Weitere Informationen finden Sie unter http://go.microsoft.com/fwlink/?LinkId=29133
3.
Die Erstellung des Projekts "C:\Users\jta6\Desktop\Titan\TitanTest\TitanTest.csproj" ist abgeschlossen (Standardziele)
-- FEHLER.

Die Erstellung des Projekts "C:\Users\jta6\Desktop\Titan\Titan.sln" ist abgeschlossen, Build Ziel(e) -- FEHLER.


Fehler beim Buildvorgang.

"C:\Users\jta6\Desktop\Titan\Titan.sln" (Build Ziel) (1) ->
"C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj" (Standardziel) (2) ->
(ResolveAssemblyReferences Ziel) ->
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: Konflikte zwischen
 verschiedenen Versionen der gleichen abhängigen Assembly wurden gefunden. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csp
roj]


"C:\Users\jta6\Desktop\Titan\Titan.sln" (Build Ziel) (1) ->
"C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj" (Standardziel) (2) ->
(CoreCompile Ziel) ->
  Bootstrap\Options.cs(24,51): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(27,52): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(30,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(33,46): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(36,47): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(39,48): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(42,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(45,44): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(48,43): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(55,42): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Bootstrap\Options.cs(60,41): error CS1519: Ungültiges Token '=' in Klasse, Struktur oder Schnittstellenmemberdeklarat
ion. [C:\Users\jta6\Desktop\Titan\Titan\Titan.csproj]
  Sharecode\ShareCode.cs(78,20): error CS1056: Unerwartetes Zeichen '$'. [C:\Users\jta6\Desktop\Titan\Titan\Titan.cspro
j]

    1 Warnung(en)
    12 Fehler

Verstrichene Zeit 00:00:01.98
An error occurred when executing task 'Build'.
Error: MSBuild: Process returned an error (exit code 1).
```

**Comment by Marc3842h** [comment]
You probably need to install the latest .NET SDK (with C# 9 support). In order to do that, please install [Visual Studio 2017](https://www.visualstudio.com/downloads/) and check in the installation progress the installation of the .NET SDK. 

After the installation successfully finished, you should be able to build Titan.

**Comment by Enzyy** [comment]
I already had every SDK / .Net packages in VS17 installed. i reinstalled everything and installed the .Net 4.62 DEV-Pack from MS... Still dont work i guess i should stop and just wait for a new release with the nice UI :P

**Comment by Marc3842h** [comment]
I don't know if you can access it but you can download the latest CI Build from AppVeyor: https://ci.appveyor.com/project/Marc3842h/titan-kr2ki/build/1.0.180/artifacts

**Comment by Marc3842h** [comment]
By the way, `[Microsoft .NET Framework, Version 4.0.30319.42000]` you're using the .NET Framework 4.0 when building Titan, maybe try to force the usage of .NET 4.5 somehow, I don't have much experience with the .NET Framework on Windows.

**Comment by Enzyy** [comment]
Thank you for your help. I just downloaded linux and build it. but now i got this failure: ```
Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Titan.Web.WebAPIKeyResolver.ParseKeyFile()
   bei Titan.Titan.Main(String[] args)
``
```

**Comment by Marc3842h** [comment]
Did you input a valid Steam Web API Key?

**Comment by Enzyy** [comment]
i cant the full log: ```
14:10:22 [Main] DEBUG Titan - Startup: Loading Serilog <-> Common Logging Bridge.
14:10:22 [Main] DEBUG Titan - Startup: Loading Quartz.NET.
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Default Quartz.NET properties loaded from embedded resource file
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Using default implementation for object serializer
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Using default implementation for ThreadExecutor
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Quartz Scheduler v.2.5.0.0 created.
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - RAMJobStore initialized.
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Scheduler meta-data: Quartz Scheduler (v2.5.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler 'DefaultQuartzScheduler' initialized
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler version: 2.5.0.0
14:10:22 [Main] INFORMATION Quartz.NET Scheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
14:10:22 [Main] DEBUG Titan - Startup: Refreshing Steam Universe list.
14:10:22 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
14:10:23 [Main] DEBUG Titan - Startup: Parsing Command Line Arguments.
14:10:23 [Main] INFORMATION Titan - The arguments --target and --mode were omitted - opening the UI.
14:10:23 [Main] DEBUG Titan - Startup: Loading Web API Key, Victim Tracker, Account Manager, UI Manager and Ban Manager.

Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Titan.Web.WebAPIKeyResolver.ParseKeyFile()
   bei Titan.Titan.Main(String[] args)
```

**Comment by Marc3842h** [comment]
Fixed with 8495159, please try again with latest release.

**Comment by Enzyy** [comment]
lol. I dont know why it dont work: ```
14:47:10 [Main] WARNING AccountManager - Less than 11 (only 7) accounts have been parsed. Atleast 11 accounts are required to get a target into Overwatch.

Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Eto.Forms.MessageBox.Show(Control parent, String text, String caption, MessageBoxButtons buttons, MessageBoxType type, MessageBoxDefaultButton defaultButton)
   bei Titan.Managers.AccountManager.ParseAccountFile()
   bei Titan.Titan.Main(String[] args)

```

**Comment by Marc3842h** [comment]
Should be fixed with 12c9ce3, please try again.

**Comment by Enzyy** [comment]
Thanks for your try but no, im not lucky - Still the same error

**Comment by 2ez4tuX** [comment]
even i cannot build in widnows can you please check the log https://pastebin.com/S5Gzceks

**Comment by Marc3842h** [comment]
@Enzyy Looks like the latest Eto Beta Build has a bug with MessageBoxes. I implemented _Notifications_ instead of MessageBoxes in 921c2ae. Could you try it out with the latest source code?

@2ez4tuX Do you have Visual Studio 2017 with .NET SDK installed? If not, please install it.

**Comment by Enzyy** [comment]
Thanks. Now i got a similar error : ```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Titan.Managers.AccountManager.ParseAccountFile()
   bei Titan.Titan.Main(String[] args)
```

Tested like everytime in Linux/Windows 10+7

**Comment by Marc3842h** [comment]
Could you try it out with a247fac?

**Comment by Enzyy** [comment]
Thank you! Finally it work! Im so happy rn :)
